[global]
load_dotenv = false  # It will break shared environments in monorepos
hide_env_diff = true
strict_env = true

[whitelist]
prefix = [
	"/Users/aimestereo/projects/ablt",
	"/Users/aimestereo/projects/sm"
]
